[package]
name = "safe_decimal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
num-traits = "0.2.15"
wasm-bindgen = "0.2.86"

[dev-dependencies]
bigdecimal = "0.3.1"
num-rational = "0.4.1"
